import type { InferredType } from './inferrer'
import type { EnvEntry } from './parser'

export interface GenerateOptions {
  /** 是否扩展 Vite 的 ImportMetaEnv */
  augmentImportMeta: boolean
  schema: 'valibot' | 'zod' | false
}

interface EntryWithType {
  entry: EnvEntry
  inferred: InferredType
}

// ─── env.d.ts ────────────────────────────────────────────────────────────────

export function generateDts(items: EntryWithType[], options: GenerateOptions): string {
  const lines: string[] = []

  lines.push(`// Auto-generated by vite-plugin-typed-env. DO NOT EDIT.`)
  lines.push(`// Re-run vite to regenerate this file.`)
  lines.push(``)

  if (options.augmentImportMeta) {
    lines.push(`/// <reference types="vite/client" />`)
    lines.push(``)
    lines.push(`interface ImportMetaEnv {`)
    for (const { entry, inferred } of items) {
      if (entry.annotations.description) {
        lines.push(`  /** ${entry.annotations.description} */`)
      }
      const opt = inferred.isOptional ? '?' : ''
      lines.push(`  readonly ${entry.key}${opt}: ${inferred.tsType}`)
    }
    lines.push(`}`)
    lines.push(``)
    lines.push(`interface ImportMeta {`)
    lines.push(`  readonly env: ImportMetaEnv`)
    lines.push(`}`)
  } else {
    lines.push(`export interface Env {`)
    for (const { entry, inferred } of items) {
      if (entry.annotations.description) {
        lines.push(`  /** ${entry.annotations.description} */`)
      }
      const opt = inferred.isOptional ? '?' : ''
      lines.push(`  ${entry.key}${opt}: ${inferred.tsType}`)
    }
    lines.push(`}`)
  }

  return lines.join('\n')
}

// ─── env.schema.ts ───────────────────────────────────────────────────────────

export function generateLoader(items: EntryWithType[], options: GenerateOptions): string {
  const lines: string[] = []

  lines.push(`// Auto-generated by vite-plugin-typed-env. DO NOT EDIT.`)
  lines.push(``)

  if (options.schema === 'zod') {
    lines.push(`import { envSchema } from './env.schema'`)
    lines.push(``)
    lines.push(`const _parsed = envSchema.safeParse(import.meta.env)`)
    lines.push(``)
    lines.push(`if (!_parsed.success) {`)
    lines.push(`  const errors = _parsed.error.flatten().fieldErrors`)
    lines.push(`  const msg = Object.entries(errors)`)
    lines.push(`    .map(([k, v]) => \`  \${k}: \${(v as string[]).join(', ')}\`)`)
    lines.push(`    .join('\\n')`)
    lines.push(`  throw new Error(\`[env-ts] Invalid environment variables:\\n\${msg}\`)`)
    lines.push(`}`)
    lines.push(``)
    lines.push(`export const env = _parsed.data`)
    lines.push(`export default env`)
  } else {
    // 无 schema 时，直接做简单的必填检查
    const required = items.filter(({ inferred }) => !inferred.isOptional)
    lines.push(`const _raw = import.meta.env`)
    lines.push(``)
    if (required.length > 0) {
      lines.push(`const _required = [${required.map(({ entry }) => `'${entry.key}'`).join(', ')}] as const`)
      lines.push(`for (const key of _required) {`)
      lines.push(`  if (!_raw[key]) throw new Error(\`[env-ts] Missing required env var: \${key}\`)`)
      lines.push(`}`)
      lines.push(``)
    }
    lines.push(`export const env = _raw as import('./env').Env`)
    lines.push(`export default env`)
  }

  return lines.join('\n')
}

// ─── env.ts (runtime loader) ─────────────────────────────────────────────────

export function generateZodSchema(items: EntryWithType[]): string {
  const lines: string[] = []

  lines.push(`// Auto-generated by vite-plugin-typed-env. DO NOT EDIT.`)
  lines.push(`import { z } from 'zod'`)
  lines.push(``)
  lines.push(`export const envSchema = z.object({`)

  for (const { entry, inferred } of items) {
    if (entry.annotations.description) {
      lines.push(`  // ${entry.annotations.description}`)
    }
    lines.push(`  ${entry.key}: ${inferred.zodSchema},`)
  }

  lines.push(`})`)
  lines.push(``)
  lines.push(`export type Env = z.infer<typeof envSchema>`)

  return lines.join('\n')
}
